name: check
# on – определяет события, которые запускают воркфлоу
on: 
  push: 
    branches: ["ci/cd"]
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  lint:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v3
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: npm ci
      - run: npm run eslint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build-prod


