name: ci
on: 
  push:
    branches: 
      - "release"
  pull_request:
    branches:
      - "main"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run type-check
      - run: npm run eslint
